version: '3'
services:
  wordpress:
    image: pedal_wordpress:1.0
    depends_on:
      - db
      - pedal_db
    restart: always
    volumes: 
      - ./wp_data:/var/www/html
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_db_password
      WORDPRESS_DB_HOST: db:3306
      PEDAL_DB_HOST: pedal_db

  db:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_db_password

  pedal_db:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    restart: always
    volumes:
      - ./pedal_db:/var/opt/mssql/data
      - ./sql_scripts:/sql_scripts
    # ports:
    #   - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd
      MSSQL_PID: Express
